#include "agent/reflection-json.h"
#include <nlohmann/json.hpp>
using json = nlohmann::ordered_json;
bool common_reflection_parse_json(const std::string & text, common_reflection_result & result, std::string & error, size_t max_operations) {
    try { auto j = json::parse(text); result = {}; if (!j.is_object() || !j.contains("decision") || !j["decision"].is_string()) { error = "reflection must be a JSON object with decision"; return false; }
        const auto d = j["decision"].get<std::string>(); if (d == "accept") result.decision = common_reflection_decision::accept; else if (d == "revise") result.decision = common_reflection_decision::revise; else if (d == "replan") result.decision = common_reflection_decision::replan; else if (d == "request_action") result.decision = common_reflection_decision::request_action; else if (d == "abort") result.decision = common_reflection_decision::abort; else { error = "unsupported reflection decision"; return false; }
        result.ready_to_answer = j.value("ready_to_answer", false); result.confidence = j.value("confidence", 0.5f); if (j.contains("revision_guidance")) for (const auto & v : j["revision_guidance"]) { if (!v.is_string()) { error = "revision guidance must be strings"; return false; } result.revision_guidance.push_back(v.get<std::string>()); }
        if (j.contains("operations")) { if (!j["operations"].is_array() || j["operations"].size() > max_operations) { error = "too many reflection operations"; return false; } for (const auto & item : j["operations"]) { if (!item.is_object() || !item.contains("kind") || !item["kind"].is_string()) { error = "invalid reflection operation"; return false; } common_plan_operation op; const auto kind = item["kind"].get<std::string>(); if (kind == "complete_step") op.kind = common_plan_operation_kind::complete_step; else if (kind == "activate_step") op.kind = common_plan_operation_kind::activate_step; else if (kind == "set_next_action") op.kind = common_plan_operation_kind::set_next_action; else { error = "unsupported reflection operation"; return false; } op.reason_summary = item.value("reason_summary", std::string{}); if (op.kind == common_plan_operation_kind::set_next_action) { if (!item.contains("value") || !item["value"].is_string()) { error = "set_next_action requires value"; return false; } op.value = item["value"].get<std::string>(); } else { if (!item.contains("step_id") || !item["step_id"].is_string()) { error = "step reflection operation requires step_id"; return false; } op.step_id = item["step_id"].get<std::string>(); } result.proposed_plan_operations.push_back(std::move(op)); } } error.clear(); return true;
    } catch (const json::exception &) { error = "malformed reflection JSON"; return false; }
}
